env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - next/core-web-vitals
  - plugin:@typescript-eslint/recommended
  - plugin:@next/next/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
  project:
    - './tsconfig.json'
plugins:
  - '@typescript-eslint'
  - 'prettier'
  - 'react'
  - '@next/eslint-plugin-next'
  - '@emotion'
  - react-hooks
rules:
  linebreak-style:
    - 'error'
    - 'unix'
  require-jsdoc:
    - 0
  react/prop-types:
    - 0
  camelcase:
    - 0
  new-cap:
    - 0
  no-console:
    - 1
  valid-jsdoc:
    - 0
